service: list-manager

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-west-2

resources: # CloudFormation template syntax from here on.
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: authTable
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: expires_at

functions:
  auth:
    handler: handler.auth
    events:
      - httpApi: "GET /auth"
  callback:
    handler: handler.callback
    events:
      - httpApi: "POST /callback"
  info:
    timeout: 30
    handler: handler.info
    events:
      - httpApi: "GET /info"
  add:
    timeout: 30
    handler: handler.add_to_list
    events:
      - httpApi: "POST /add"
  remove:
    timeout: 30
    handler: handler.remove_from_list
    events:
      - httpApi: "POST /remove"

package:
  patterns:
    - "!node_modules"
    - "!list-manager"

custom:
  serverless-offline:
    httpPort: 4000
  dynamodb:
    ttl:
      - table: authTable
        field: your-ttl-property-name

plugins:
  - serverless-python-requirements
  - serverless-offline
